version: "3.2"

services:
  postgres:
    image: postgres
    volumes:
      - .back/db/cliente.sql:/docker-entrypoint-initdb.d/cliente.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  front:
    build: ./front
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      # - /app/node_modules
      - ./front/src:/app/src
    ports:
      - 80:3000
    networks:
      - frontend

networks:
  frontend:
    driver: bridge