version: "3.2"

services:
  front:
    build: ./front
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      # - /app/node_modules
      - ./front/src:/app/src
    ports:
      - 80:3000